name: tokenizer
description: Converts a stream of strings into a stream of tokens separated by delimiters
version: 1.0.0
homepage: https://github.com/lesnitsky/tokenizer

environment:
  sdk: ">=2.7.0 <3.0.0"

dev_dependencies: { test: ^1.21.1 }
