name: tokenizer
description: Converts a stream of strings into a stream of tokens separated by delimiters
version: 1.0.1
homepage: https://github.com/lesnitsky/tokenizer

environment:
  sdk: '>=3.5.0 <4.0.0'

dev_dependencies: { test: ^1.26.3 }
